const MARTECH_POPULAR_TAGS = [
  "CDP", "CRM", "Loyalty", "Marketing Automation", "Data Analytics", "AI", "Chatbot", 
  "Social Listening", "Influencer Marketing", "E-Commerce", "Digital Agency", 
  "Consulting", "Cloud", "Media", "Software Development",
  "Performance Marketing", "LINE OA"
];

const MARTECH_COMPANIES = [
  { 
    id: "choco-crm", 
    nameTh: "บริษัท ช็อคโก้ คาร์ด เอ็นเตอร์ไพรส์ จำกัด", 
    nameEn: "CHOCO CARD ENTERPRISE COMPANY LIMITED", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-2.png", 
    businessType: "Tech Platform", 
    contact: "Pitiporn Seeiam", 
    phone: "099-382-6945", 
    email: "pitiporn.se@chococrm.com", 
    website: "https://chococrm.com/", 
    description: "Choco CRM มีความเชี่ยวชาญด้าน Loyalty Program และการทำ Marketing Automation ผ่านแพลตฟอร์มที่ออกแบบมาเพื่อช่วยธุรกิจของลูกค้าให้เกิดประโยชน์สูงสุด",
    tags: ["CRM", "Loyalty", "Marketing Automation", "CDP", "Software Development"]
  },
  { 
    id: "digital-integrate", 
    nameTh: "บริษัท ดิจิทัล อินทิเกรท จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-3.png", 
    businessType: "Tech Platform", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "Digital Integrate เชี่ยวชาญด้าน Performance Media และการสร้าง Landing Page เพื่อเพิ่มยอดขาย พร้อมระบบ Reporting Dashboard ที่ปรับแต่งได้",
    tags: ["Performance Marketing", "Digital Agency", "Data Analytics"]
  },
  { 
    id: "crescendo-lab", 
    nameTh: "บริษัท เครสเซนโด้ แล็บ จำกัด", 
    nameEn: "CRESCENDO LAB CO., LTD.", 
    logo: "https://martechthai.org/wp-content/uploads/2026/01/CresendoLabBlack.png", 
    businessType: "Tech Platform", 
    contact: "ออฟ วัชรธร มีเดช", 
    phone: "063-324-6535", 
    email: "aoffy.mee@cresclab.com", 
    website: "https://www.cresclab.com/th", 
    description: "Crescendo Lab คือผู้ให้บริการโซลูชันการตลาดอัตโนมัติและการจัดการลูกค้าสัมพันธ์ (LINE CRM) ชั้นนำสำหรับ LINE Official Account",
    tags: ["CRM", "Marketing Automation", "LINE OA", "Software Development"]
  },
  { 
    id: "shipnity", 
    nameTh: "บริษัท ชิปนิตี้ จำกัด", 
    nameEn: "Shipnity Co.,Ltd.", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-12.png", 
    businessType: "Tech Platform", 
    contact: "ภาวิตา", 
    phone: "083-959-6263", 
    email: "pawita@shipnity.com", 
    website: "http://www.shipnity.com", 
    description: "Shipnity ระบบจัดการร้านค้าออนไลน์ (Order Management) และคลังสินค้า (Max Warehouse) พร้อมฟีเจอร์ POS และเชื่อมต่อ E-Marketplace ครบวงจร",
    tags: ["E-Commerce", "Management System", "POS", "Tech Platform"]
  },
  { 
    id: "data-first", 
    nameTh: "บริษัท ดาต้า เฟิร์ส จำกัด", 
    nameEn: "Data First Co., Ltd.", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-13.png", 
    businessType: "Agency", 
    contact: "ชญานิศ เติมแก้ว", 
    phone: "02-354-3570", 
    email: "support@datafirst.id", 
    website: "https://www.datafirst.co.th/", 
    description: "Data First ที่ปรึกษาและผู้ให้บริการโซลูชันด้านข้อมูลครบวงจร ทั้ง Data Science, AI/Chatbot และ Product อย่าง FLOW F&B Analytics สำหรับธุรกิจร้านอาหาร",
    tags: ["Data Analytics", "Consulting", "AI", "MarTech Solution"]
  },
  { 
    id: "dgs-digital", 
    nameTh: "บริษัท ดีจีเอส ดิจิตอล จำกัด", 
    nameEn: "DGS Digital Co.,Ltd", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-15.png", 
    businessType: "Agency", 
    contact: "ธันย์ชนก อุณหชาติ", 
    phone: "099-226-4456", 
    email: "sale@digisaws.com", 
    website: "https://digisaws.com/", 
    description: "DGS Marketing Engineers เอเจนซี่การตลาด B2B แบบครบวงจร (Full-Funnel) เชี่ยวชาญด้านกลยุทธ์ Content และ Creative เพื่อสร้างการเติบโตให้ธุรกิจอุตสาหกรรม",
    tags: ["B2B Marketing", "Digital Agency", "Strategy", "Content"]
  },
  { 
    id: "demeter-ict", 
    nameTh: "บริษัท ดีมีเตอร์ ไอซีที จำกัด", 
    nameEn: "DEMETER ICT CO.,LTD.", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-16.png", 
    businessType: "Consult", 
    contact: "ดุจฤดี ฉมาภินันท์", 
    phone: "087-488-9228", 
    email: "dutrudee@dmit.co.th", 
    website: "https://dmit.co.th", 
    description: "Demeter ICT คือตัวแทนจำหน่ายและติดตั้ง Google Workspace และ Zendesk อย่างเป็นทางการ เชี่ยวชาญด้าน DX, CRM และ Cloud Solutions มายาวนาน",
    tags: ["Consulting", "Cloud", "CRM", "Zendesk Partner"]
  },
  { 
    id: "dentsu", 
    nameTh: "บริษัท เดนท์สุ โฮลดิ้งส์ (ประเทศไทย) จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-17.png", 
    businessType: "Agency", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "",
    tags: ["Digital Agency", "Media"]
  },
  { 
    id: "3ds-interactive", 
    nameTh: "บริษัท ทรีดีเอส อินเตอร์แอคทีฟ จำกัด", 
    nameEn: "3DS Interactive Co., Ltd.", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-18.png", 
    businessType: "Tech Platform", 
    contact: "ชนัญญา เลาหะพันธุ์", 
    phone: "090-983-2659", 
    email: "contact@3dsinteractive.com", 
    website: "https://www.3dsinteractive.com/", 
    description: "3DS Interactive ผู้พัฒนา 'Pam Marketing Automation' แพลตฟอร์ม CDP และ Marketing Automation ระดับ Enterprise ที่ช่วยบริหารจัดการข้อมูลลูกค้าและแคมเปญ",
    tags: ["CDP", "Marketing Automation", "Tech Platform", "Enterprise Solution"]
  },
  { 
    id: "tellscore", 
    nameTh: "บริษัท เทลสกอร์ จำกัด", 
    nameEn: "Tellscore", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-20.png", 
    businessType: "Tech Platform", 
    contact: "Customer Service", 
    phone: "09-5629-8996", 
    email: "contact@tellscore.com", 
    website: "https://th.tellscore.com/th", 
    description: "Tellscore ผู้นำด้าน Influencer Marketing Automation Platform ของไทย เชื่อมต่อแบรนด์กับ Influencer กว่า 90,000 รายด้วยระบบ AI พร้อมบริการ Media Buy & Optimization",
    tags: ["Influencer Marketing", "Tech Platform", "AI", "Digital Agency"]
  },
  { 
    id: "nation-news", 
    nameTh: "บริษัท เนชั่น นิวส์ จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-22.png", 
    businessType: "Media", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "เนชั่น นิวส์ สื่อชั้นนำที่นำเสนอข่าวสารและโซลูชันการตลาดดิจิทัลผ่านแพลตฟอร์มต่างๆ ทั้ง Online และ On-ground",
    tags: ["Media", "Publisher", "Online Media", "News"]
  },
  { 
    id: "buzzebees", 
    nameTh: "บริษัท บัซซี่บีส์ จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-24.png", 
    businessType: "Tech Platform", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "Buzzebees ผู้นำด้าน CRM & Privilege Platform อันดับ 1 ของไทย ให้บริการ E-Commerce Enabler และ Loyalty Solution ครบวงจรสำหรับองค์กรขนาดใหญ่",
    tags: ["CRM", "Loyalty", "E-Commerce", "Tech Platform", "Food Delivery"]
  },
  { 
    id: "btask", 
    nameTh: "บริษัท บีแทสก์ คอนซัลติ้ง จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-25.png", 
    businessType: "Agency", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "Btask Consulting ผู้ให้บริการระบบจองคิว (Queue Booking) และระบบสะสมแต้มผ่าน LINE OA ยกระดับบริการสำหรับธุรกิจความงามและสุขภาพ",
    tags: ["Booking System", "Loyalty", "LINE OA", "Software Development"]
  },
  { 
    id: "bookola", 
    nameTh: "บริษัท บุโคล่า จำกัด", 
    nameEn: "BOOKOLA CO., LTD.", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-26.png", 
    businessType: "Tech Platform", 
    contact: "กฤษฎา หลินภัทรชัย", 
    phone: "087-567-8970", 
    email: "fame.kritsada@bookola.ai", 
    website: "https://www.bookola.ai", 
    description: "BOOKOLA คือ AI-MarTech สำหรับโรงแรม มีฟีเจอร์ AI Chatbot ตอบแชทอัตโนมัติ, Booking Engine จองห้องพักโดยตรง และระบบจัดการข้อมูลโรงแรม",
    tags: ["Hotel Tech", "AI", "Chatbot", "Booking System"]
  },
  { 
    id: "privage", 
    nameTh: "บริษัท พริเวจ แอป จำกัด", 
    nameEn: "PRIVAGE APP COMPANY LIMITED", 
    logo: "https://martechthai.org/wp-content/uploads/2025/09/Privage_Logo.png", 
    businessType: "Tech Platform", 
    contact: "K.Sai", 
    phone: "092-268-5996", 
    email: "sai@privageapp.com", 
    website: "https://privageapp.com/th", 
    description: "พริเวจ CRM Solution บัตรสะสมแต้มด้วยเบอร์โทรศัพท์ ใช้งานง่ายผ่าน LINE OA",
    tags: ["CRM", "Loyalty", "LINE OA"]
  },
  { 
    id: "predictive", 
    nameTh: "บริษัท พรีดิกทิฟ จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-28.png", 
    businessType: "Agency", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "Predictive ที่ปรึกษาด้าน CX และ Data Intelligent ชั้นนำ เชี่ยวชาญด้าน CDP, Data Analytics และการทำ Personalization เพื่อขับเคลื่อนธุรกิจด้วยข้อมูล",
    tags: ["Data Analytics", "Consulting", "CX", "CDP", "Personalization"]
  },
  { 
    id: "primoworld", 
    nameTh: "บริษัท พรีโมเวิร์ล จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-29.png", 
    businessType: "Tech Platform", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "Primo แพลตฟอร์ม CRM และ Loyalty Program แบบ Omnichannel ที่เชื่อมต่อแบรนด์กับลูกค้าผ่านทุกช่องทาง พร้อมระบบจัดการสมาชิกและสิทธิพิเศษ",
    tags: ["CRM", "Loyalty", "Omnichannel", "Tech Platform", "CDP"]
  },
  { 
    id: "marketingtech", 
    nameTh: "บริษัท มาร์เก็ตติ้งเทค จำกัด", 
    nameEn: "Marketingtech Company Limited", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-32.png", 
    businessType: "Agency", 
    contact: "จิตติพงศ์ เลิศประดิษฐ์", 
    phone: "095-879-9955", 
    email: "martechthai@gmail.com", 
    website: "http://www.martechthai.com", 
    description: "ชุมชนผู้ใช้มาร์เทค",
    tags: ["Community", "Media", "Consulting"]
  },
  { 
    id: "megenius-aiya", 
    nameTh: "บริษัท มีจีเนียส จำกัด", 
    nameEn: "Megenius Co.,Ltd", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-33.png", 
    businessType: "Tech Platform", 
    contact: "คุณอัจฉริยะ ดาโรจน์", 
    phone: "06-2574-5669", 
    email: "Atchariya@aiya.ai", 
    website: "https://aiyabeacon.com/", 
    description: "AIYA (โดย Megenius) ผู้นำด้าน Location-based Marketing และ AI CRM บริหารความสัมพันธ์ลูกค้าผ่าน LINE OA พร้อมระบบ AiBeacon เจาะกลุ่มลูกค้าหน้าร้าน",
    tags: ["Marketing Automation", "Location-based", "AI", "CRM", "LINE OA"]
  },
  { 
    id: "readyplanet", 
    nameTh: "บริษัท เรดดี้แพลนเน็ต จำกัด (มหาชน)", 
    nameEn: "Readyplanet Public Company Limited", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-35.png", 
    businessType: "Tech Platform", 
    contact: "บุรินทร์​ เกล็ดมณี", 
    phone: "082-727-9999", 
    email: "info@readyplanet.com", 
    website: "https://www.readyplanet.com/", 
    description: "Readyplanet ผู้ให้บริการ All-in-One Sale & Marketing Platform ครอบคลุมเว็บไซต์, R-CRM, R-Widget และระบบ Booking สำหรับธุรกิจไทย",
    tags: ["Tech Platform", "CRM", "Marketing Automation", "Website", "Booking System"]
  },
  { 
    id: "real-smart", 
    nameTh: "บริษัท เรียล สมาร์ท จำกัด (มหาชน)", 
    nameEn: "REAL SMART PUBLIC COMPANY LIMITED", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-37.png", 
    businessType: "Tech Platform", 
    contact: "ณิญาพัณณ์ รัตนาวงศ์ศรี", 
    phone: "099-259-2895", 
    email: "Niyapunn.r@realsmart.co.th", 
    website: "https://www.realsmart.co.th/", 
    description: "Real Smart ผู้ให้บริการ Real Listening (Social Listening Tool) และ Data Analytics ครบวงจร พร้อมทีมวิเคราะห์ข้อมูลเพื่อหา Insight ในโลกออนไลน์",
    tags: ["Social Listening", "Data Analytics", "AI", "Tech Platform"]
  },
  { 
    id: "robolingo", 
    nameTh: "บริษัท โรโบลิงโก้ จำกัด", 
    nameEn: "Robolingo Co.,Ltd.", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-38.png", 
    businessType: "Tech Platform", 
    contact: "ชลธิชา อภิชนพงศา", 
    phone: "02-821-5535 กด 3", 
    email: "chonthicha.a@robolingo.ai", 
    website: "https://zwiz.ai", 
    description: "ZWIZ.AI (โดย Robolingo) แชทบอท AI อัจฉริยะ ช่วยตอบแชท ปิดการขาย และสรุปยอดออเดอร์ (Social Commerce) รองรับ Facebook, LINE และ Instagram",
    tags: ["Chatbot", "AI", "Social Commerce", "Automation"]
  },
  { 
    id: "likeme", 
    nameTh: "บริษัท ไลค์ มี จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-39.png", 
    businessType: "Agency", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "Likeme Agency ดิจิทัลเอเจนซี่ที่โดดเด่นด้าน Creative Content และ Technology Marketing บริหารจัดการแบรนด์ดังอย่าง Infographic Thailand",
    tags: ["Digital Agency", "Content", "Creative", "Influencer Marketing"]
  },
  { 
    id: "onemobby", 
    nameTh: "บริษัท วันม๊อบบี้ จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-40.png", 
    businessType: "Tech Platform", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "One Mobby ผู้ให้บริการ MarTech Solution ครบวงจร ทั้ง Thaibulksms, Movider และแพลตฟอร์ม Chatbot/CDP เพื่อช่วยธุรกิจทำ Digital Transformation",
    tags: ["Tech Platform", "SMS Marketing", "Chatbot", "CDP"]
  },
  { 
    id: "ymdot", 
    nameTh: "บริษัท วายเอ็มดอท สตูดิโอ จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-41.png", 
    businessType: "Agency", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "",
    tags: ["Agency", "Creative"]
  },
  { 
    id: "winter-egency", 
    nameTh: "บริษัท วินเทอร์อีเจนซี่ จำกัด", 
    nameEn: "WINTER EGENCY", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-42.png", 
    businessType: "Tech Platform", 
    contact: "Chutiphan Sukhanthachan", 
    phone: "092-465-4461", 
    email: "chutiphan@winter.co.th", 
    website: "https://www.winter.co.th/", 
    description: "Winter Egency เอเจนซี่การตลาดดิจิทัลที่ขับเคลื่อนด้วย Data และ Tech เป็นพาร์ทเนอร์ด้าน CDP และเชี่ยวชาญ E-Commerce Strategy",
    tags: ["Digital Agency", "Data Driven", "CDP", "Performance Marketing"]
  },
  { 
    id: "way-maker", 
    nameTh: "บริษัท เวย์ เมคเกอร์ จำกัด", 
    nameEn: "Way Maker Co., Ltd.", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-44.png", 
    businessType: "Agency", 
    contact: "ภัทรานิษฐ์ สุวรรณวัฒน์", 
    phone: "099-005-9440", 
    email: "pattranit@waymaker.co.th", 
    website: "https://www.waymaker.co.th/", 
    description: "Way Maker ที่ปรึกษากลยุทธ์การตลาดดิจิทัล (Digital Marketing Consulting) เน้นการสร้างแบรนด์และการใช้ AI เข้ามาช่วยเพิ่มประสิทธิภาพการทำงาน",
    tags: ["Consulting", "Digital Marketing", "AI", "Strategy"]
  },
  { 
    id: "insight-era", 
    nameTh: "บริษัท อินไซท์ เอรา จำกัด", 
    nameEn: "InsightERA Co., Ltd.", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-48.png", 
    businessType: "Tech Platform", 
    contact: "คุณนิปปอน", 
    phone: "065-524-7861", 
    email: "naporn.p@insightera.co.th", 
    website: "https://www.insightera.co.th", 
    description: "InsightEra ผู้ให้บริการ 'DOM' Social Listening Tool และบริการวิเคราะห์ข้อมูลการตลาด (Marketing Analytics) ด้วยเทคโนโลยี AI และ NLP ภาษาไทย",
    tags: ["Social Listening", "Data Analytics", "AI", "MarTech Solution"]
  },
  { 
    id: "ai-system", 
    nameTh: "บริษัท เอ ไอ ซิสเต็ม จำกัด", 
    nameEn: "A I System Co., Ltd.", 
    logo: "https://martechthai.org/wp-content/uploads/2026/01/01_A-I-SYSTEM_M-1.png", 
    businessType: "Tech Platform", 
    contact: "เกรียงไกร สุทธินราธร", 
    phone: "086-465-6519", 
    email: "kriengkrai.s@aisystem.co.th", 
    website: "https://www.aisystem.co.th", 
    description: "AI System ผู้เชี่ยวชาญด้าน Digital Transformation และ Software Development พัฒนาโซลูชันเฉพาะสำหรับองค์กร",
    tags: ["Digital Transformation", "Software Development", "Tech Partner", "Consulting"]
  },
  { 
    id: "asap-project", 
    nameTh: "บริษัท เอแซป โปรเจคท์ จำกัด", 
    nameEn: "ASAP Project", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-50.png", 
    businessType: "Agency", 
    contact: "ธิติ คุณาจิตพิมล", 
    phone: "094-551-9876", 
    email: "thiti@asapproject.co", 
    website: "https://www.asapproject.co", 
    description: "ASAP Project ที่ปรึกษากลยุทธ์ Digital Transformation ช่วยวางแผน Roadmap เลือก Vendor และบริหารโครงการ CRM, ERP, POS ให้ธุรกิจ",
    tags: ["Consulting", "Digital Transformation", "Strategy", "Project Management", "CRM"]
  },
  { 
    id: "m-intelligence", 
    nameTh: "บริษัท เอ็ม อินเทลลิเจนซ์ จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-52.png", 
    businessType: "Tech Platform", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "M Intelligence ผู้ให้บริการ Salesforce CRM ที่ได้รับอนุญาต (Reseller) เชี่ยวชาญด้าน Sales Cloud, Marketing Cloud และการเชื่อมต่อ LINE OA",
    tags: ["Tech Platform", "CRM", "Marketing Automation", "Salesforce Partner", "LINE OA"]
  },
  { 
    id: "emetworks", 
    nameTh: "บริษัท เอเมทเวิร์คส์ จำกัด", 
    nameEn: "Emetworks Company Limited", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-53.png", 
    businessType: "Tech Platform", 
    contact: "Jenjira Sangvareethip", 
    phone: "089-899-2033", 
    email: "jenjira@emetworks.com", 
    website: "http://www.emetworks.com", 
    description: "Emetworks ที่ปรึกษาด้าน Innovation และ Digital Transformation เน้นการสร้างธุรกิจใหม่ (Venture Building) และพัฒนา AI Product เช่น EX10 CRM",
    tags: ["Consulting", "Digital Transformation", "Venture Building", "AI", "CRM"]
  },
  { 
    id: "dpu", 
    nameTh: "มหาวิทยาลัยธุรกิจบัณฑิตย์", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-56.png", 
    businessType: "University", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "",
    tags: ["Education", "Academic"]
  },
  { 
    id: "ssru", 
    nameTh: "มหาวิทยาลัยราชภัฏสวนสุนันทา", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/03/Company-Logo-57.png", 
    businessType: "University", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "",
    tags: ["Education", "Academic"]
  },
  { 
    id: "bitkub", 
    nameTh: "บริษัท บิทคับ แคปปิตอล กรุ๊ป โฮลดิ้งส์ จำกัด", 
    nameEn: "Bitkub Capital Group Holdings Co., Ltd.", 
    logo: "https://martechthai.org/wp-content/uploads/2024/09/Company-Logo-59.png", 
    businessType: "Tech Platform", 
    contact: "ธนัท มั่นธนาสารชัย", 
    phone: "086-379-9550", 
    email: "oat.thanut@bitkub.com", 
    website: "https://www.bitkubcapital.com/", 
    description: "Bitkub Capital ผู้นำด้าน Blockchain Technology และ Digital Asset ของไทย ให้บริการ Bitkub Chain Solution สำหรับธุรกิจและ NFT Loyalty Platform",
    tags: ["Blockchain", "FinTech", "Digital Asset", "NFT", "Loyalty"]
  },
  { 
    id: "anymind", 
    nameTh: "บริษัท เอนี่มายด์ จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/09/Company-Logo-58.png", 
    businessType: "Tech Platform", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "AnyMind Group ผู้ให้บริการ End-to-End Commerce Platform ครอบคลุม AnyTag (Influencer), AnyManager (Publisher) และ E-Commerce Enabler",
    tags: ["Tech Platform", "Influencer Marketing", "E-Commerce", "AdTech", "AI"]
  },
  { 
    id: "ydm", 
    nameTh: "บริษัท วายดีเอ็ม (ไทยแลนด์) จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/09/Company-Logo-64.png", 
    businessType: "Agency", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "YDM Thailand เอเจนซี่การตลาดที่ใช้ Data และ AI ขับเคลื่อนความสำเร็จ (Creative & MarTech) ให้บริการ Full-Funnel Marketing Solutions",
    tags: ["Digital Agency", "Data Driven", "AI", "Performance Marketing", "MarTech"]
  },
  { 
    id: "kinesso", 
    nameTh: "บริษัท คิเนสโซ (ประเทศไทย) จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/09/Company-Logo-61.png", 
    businessType: "Agency", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "Kinesso Thailand (ในเครือ IPG) ผู้ให้บริการ Marketing Intelligence และ Data-Driven Performance Marketing ระดับโลก",
    tags: ["Media Agency", "Data Analytics", "Performance Marketing", "AdTech"]
  },
  { 
    id: "dataxet", 
    nameTh: "บริษัท ดาต้าเซ็ต จำกัด", 
    nameEn: "Dataxet Limited", 
    logo: "https://martechthai.org/wp-content/uploads/2025/12/dataxet-logo-Apassaree-Chongsathien.png", 
    businessType: "Tech Platform", 
    contact: "อาภัสรี จงเสถียร", 
    phone: "085-070-1649", 
    email: "apassaree@dataxet.com", 
    website: "https://www.dataxet.co", 
    description: "Dataxet ผู้ให้บริการ Media Intelligence ผ่านแพลตฟอร์ม 'DXT360' ที่รวม Social Listening และ Media Monitoring เพื่อวิเคราะห์ภาพลักษณ์แบรนด์",
    tags: ["Media Intelligence", "Social Listening", "PR", "Data Analytics"]
  },
  { 
    id: "funcrowd", 
    nameTh: "บริษัท ฟันคราวด์ จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/09/Company-Logo-71.png", 
    businessType: "Tech Platform", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "Funcrowd แพลตฟอร์ม CRM และระบบสมาชิกออนไลน์ (Membership) ครบวงจร เชื่อมต่อ LINE OA สะสมแต้ม และ E-Commerce สำหรับร้านค้า",
    tags: ["CRM", "Loyalty", "Tech Platform", "LINE OA", "E-Commerce"]
  },
  { 
    id: "creative-era", 
    nameTh: "บริษัท ครีเอทีฟ อีร่า จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/09/Company-Logo-70.png", 
    businessType: "Agency", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "Creative Era เอเจนซี่โฆษณาที่ผสมผสานความคิดสร้างสรรค์กับเทคโนโลยีสื่อสารการตลาด",
    tags: ["Digital Agency", "Creative", "Marketing Communication"]
  },
  { 
    id: "go-online", 
    nameTh: "บริษัท โก ออนไลน์ เอเจนซี่ จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2024/09/Company-Logo-69.png", 
    businessType: "Agency", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "Go Online เอเจนซี่การตลาดออนไลน์แบบครบวงจร เชี่ยวชาญการยิงโฆษณา (Ads Optimization) และ Social Media Management",
    tags: ["Digital Agency", "Online Marketing", "Performance Marketing"]
  },
  { 
    id: "chillpay", 
    nameTh: "บริษัท พระอินทร์ ฟินเทค จำกัด", 
    nameEn: "PraIn FinTech Co., Ltd.", 
    logo: "https://martechthai.org/wp-content/uploads/2024/09/Company-Logo-68.png", 
    businessType: "Tech Platform", 
    contact: "Nattinan Phonphichai", 
    phone: "094-887-6882", 
    email: "business@chillpay.co", 
    website: "https://www.chillpay.co", 
    description: "ChillPay is a licensed payment service provider",
    tags: ["Payment Gateway", "FinTech"]
  },
  { 
    id: "unicronet", 
    nameTh: "บริษัท อินเทลลิเจนท์ คอนซัลติ้ง แอนด์ บิสซิเนส ดีเวลลอปเมนท์ จำกัด", 
    nameEn: "Intelligent Consulting and Business Development Co.,Ltd.", 
    logo: "https://martechthai.org/wp-content/uploads/2025/12/S__7012405.png", 
    businessType: "Agency", 
    contact: "ชญานิศ จิตรีปลื้ม", 
    phone: "094-616-3651", 
    email: "chayanis@icbdconsulting.com", 
    website: "http://www.unicronet.com/", 
    description: "Unicronet ให้บริการการตลาดครบวงจร",
    tags: ["Digital Agency", "Consulting", "MarTech"]
  },
  { 
    id: "iship", 
    nameTh: "บริษัท ไอชิพ เซอร์วิส จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2025/01/NEW-iShip-CI-guideline-RGB-09.05.2567.png", 
    businessType: "Tech Platform", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "",
    tags: ["Logistics", "E-Commerce", "Tech Platform"]
  },
  { 
    id: "relationship", 
    nameTh: "บริษัท รีเลชั่นชิพ รีพับบลิค จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2025/03/relationship_logo.jpg", 
    businessType: "Agency", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "",
    tags: ["Agency", "PR"]
  },
  { 
    id: "via-group", 
    nameTh: "บริษัท เวีย กรุ๊ป (ประเทศไทย) จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2025/03/vb_LOGO2019.png", 
    businessType: "Tech Platform", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "",
    tags: ["Tech Platform", "Transport"]
  },
  { 
    id: "salesarm", 
    nameTh: "บริษัท เซลส์อาร์ม จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2025/04/AIM.png", 
    businessType: "Agency", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "",
    tags: ["Sales Tech", "Consulting"]
  },
  { 
    id: "dudatae", 
    nameTh: "บริษัท ดูดาเต้ จำกัด", 
    nameEn: "DUDATAE Co.,Ltd", 
    logo: "https://martechthai.org/wp-content/uploads/2025/03/S__19865615.jpg", 
    businessType: "Agency", 
    contact: "คณินณัฐ นกน้อย", 
    phone: "085-511-1129", 
    email: "nach@dudatae.co.th", 
    website: "http://www.dudatae.co.th", 
    description: "Data Design House ด้าน Research Tech",
    tags: ["Data Analytics", "Research", "Data Visualization"]
  },
  { 
    id: "hilike", 
    nameTh: "บริษัท ไฮ-ไลค์ เอเจนซี่ จำกัด", 
    nameEn: "", 
    logo: "https://martechthai.org/wp-content/uploads/2025/03/HLA-logo-png.png", 
    businessType: "Agency", 
    contact: "", 
    phone: "", 
    email: "", 
    website: "", 
    description: "",
    tags: ["Digital Agency", "Marketing"]
  },
  { 
    id: "ants", 
    nameTh: "บริษัท แอดวานซ์ เน็ตเวิร์ค เทคโนโลยี แอนด์ เซอร์วิส จํากัด", 
    nameEn: "Advance Network Technology & Services Co., Ltd.", 
    logo: "https://martechthai.org/wp-content/uploads/2025/03/ants-logo.png", 
    businessType: "Tech Platform", 
    contact: "Nattika Yaemkhayai", 
    phone: "063-495-1479", 
    email: "nattika.y@ants.co.th", 
    website: "https://www.ants.co.th/", 
    description: "ANTS คือผู้ให้บริการทางด้านการตลาดและเทคโนโลยี (Marketing Technology)",
    tags: ["MarTech", "Tech Platform", "Content"]
  },
  { 
    id: "redcarbon", 
    nameTh: "บริษัท เดอะเรดคาร์บอน จํากัด", 
    nameEn: "The Red Carbon", 
    logo: "https://martechthai.org/wp-content/uploads/2025/04/Redcarbon-IMG_1866.png", 
    businessType: "Agency", 
    contact: "เค้นท์ สเคาว์เทิ่น", 
    phone: "084-187-727", 
    email: "gent.s@theredcarbon.com", 
    website: "https://theredcarbon.com", 
    description: "The Red Carbon empowers brands with data-driven marketing",
    tags: ["Data Driven", "MarTech", "Digital Agency"]
  },
  { 
    id: "hoteliers-guru", 
    nameTh: "บริษัท โฮเทลเลียร์ ดอท กูรู (ประเทศไทย) จํากัด", 
    nameEn: "Hoteliers Dot Guru (Thailand) Co.,Ltd.", 
    logo: "https://martechthai.org/wp-content/uploads/2025/04/HG-logo.png", 
    businessType: "Tech Platform", 
    contact: "Isaya Phatthanaphakdi", 
    phone: "066-005-5320", 
    email: "isaya.p@hoteliers.guru", 
    website: "https://www.hoteliers.guru", 
    description: "Hoteliers.Guru serves boutique and independent hotels",
    tags: ["Hotel Tech", "Booking System", "Agency"]
  },
  { 
    id: "rada-richness", 
    nameTh: "บริษัท รดา ริชเนส จำกัด", 
    nameEn: "RADA Richness Co., Ltd.", 
    logo: "https://martechthai.org/wp-content/uploads/2025/09/aw_logo_rada.png", 
    businessType: "Agency", 
    contact: "K.Orn Rusada Noisong", 
    phone: "089-799-6392", 
    email: "rada.richness@gmail.com", 
    website: "https://www.radarichness.com", 
    description: "MarTech Agency ที่ใช้เทคโนโลยีขับเคลื่อนกลยุทธ์การตลาด",
    tags: ["MarTech Agency", "Strategy", "Digital Marketing"]
  },
  { 
    id: "gotitz", 
    nameTh: "บริษัท ก็อทอิทซ์ จำกัด", 
    nameEn: "GOT ITZ CO., LTD.", 
    logo: "https://martechthai.org/wp-content/uploads/2025/12/GOT-ITZ-Logo_PNG-12-Yongplut-Y.png", 
    businessType: "Agency", 
    contact: "ยงพฤทธิ์ เยี่ยงอร่ามกุล", 
    phone: "084-070-4256", 
    email: "yongplut.y@gotitz.com", 
    website: "https://www.gotitz.com", 
    description: "GOT ITZ GOT What your customer want",
    tags: ["Consulting", "MarTech", "Training"]
  },
  { 
    id: "wisesight", 
    nameTh: "บริษัท ไวซ์ไซท์ (ประเทศไทย) จำกัด", 
    nameEn: "Wisesight (Thailand) Co., Ltd.", 
    logo: "https://martechthai.org/wp-content/uploads/2025/12/primary-logo-Thanaporn-Proud-Nuchphadung-1.png", 
    businessType: "Tech Platform", 
    contact: "ฐานพร นุชผดุง", 
    phone: "088-964-9796", 
    email: "thanaporn.n@wisesight.com", 
    website: "https://wisesight.com/", 
    description: "Wisesight ผู้พัฒนา 'Zocial Eye' เครื่องมือ Social Listening อันดับ 1 ของไทย และให้บริการวิเคราะห์ข้อมูลตลาดด้วย AI เพื่อเจาะลึก Consumer Insight",
    longLogo: true,
    tags: ["Social Listening", "Data Analytics", "AI", "Tech Platform"]
  },
  { 
    id: "the-strategist", 
    nameTh: "บริษัท เดอะ สแตรททีจิสท์ จำกัด", 
    nameEn: "THE STRATEGIST CO.,LTD", 
    logo: "https://martechthai.org/wp-content/uploads/2025/12/STRAT_Brand-Logo_Black-Prear-Puchtongchai.png", 
    businessType: "Consult", 
    contact: "แพร พืชธงชัย", 
    phone: "06-5359-4229", 
    email: "contact@thestrategist.in.th", 
    website: "", 
    description: "ศูนย์กลางการเรียนรู้เพื่อยกระดับนักกลยุทธ์", 
    longLogo: true,
    tags: ["Education", "Consulting", "Strategy"]
  },
  { 
    id: "ipg-kinesso", 
    nameTh: "บริษัท ไอพีจี แอดเวอไทซิ่ง (ประเทศไทย) จำกัด", 
    nameEn: "IPG Advertising (Thailand) Limited", 
    logo: "https://martechthai.org/wp-content/uploads/2025/12/IPG_MB_Logo_RGB_Full_Black-Supalurk-Tangcharoensiri-1-scaled.jpg", 
    businessType: "Agency", 
    contact: "ศุภฤกษ์ ตั้งเจริญศิริ", 
    phone: "083-988-7711", 
    email: "supalurk.tangcharoensiri@kinesso.com", 
    website: "https://ipg-connect.com", 
    description: "Media Agency", 
    longLogo: true,
    tags: ["Media Agency", "Advertising", "Global Agency"]
  },
  { 
    id: "foretoday", 
    nameTh: "บริษัท ฟอร์ทูเดย์ จำกัด", 
    nameEn: "FORETODAY", 
    logo: "https://martechthai.org/wp-content/uploads/2025/12/ForeToday-Full-Logo-Colors-for-Light-BG-2-6-Panachai-Win-Sriprasert.png", 
    businessType: "Agency", 
    contact: "ปณชัย ศรีประเสริฐ", 
    phone: "093-264-9536", 
    email: "panachai@foretoday.asia", 
    website: "https://foretoday.asia/", 
    description: "Performance Marketing Agency", 
    longLogo: true,
    tags: ["Performance Marketing", "Digital Agency", "Consulting"]
  },
  { 
    id: "guardian-ai", 
    nameTh: "บริษัท การ์เดียน เอไอ แลบ จำกัด", 
    nameEn: "Guardian AI", 
    logo: "https://martechthai.org/wp-content/uploads/2025/12/GuardianAI-Logo-blue-Sathapon-Patanakuha.png", 
    businessType: "Tech Platform", 
    contact: "สถาพน พัฒนะคูหา", 
    phone: "092-996-9546", 
    email: "bank@guardianlab.ai", 
    website: "https://www.guardianlab.ai", 
    description: "Guardian AI พัฒนา AI Sales Solution ที่ช่วย B2B และ B2C เพิ่มยอดขายด้วยเทคโนโลยีปัญญาประดิษฐ์ วิเคราะห์ข้อมูลการขายและลูกค้า",
    longLogo: true,
    tags: ["AI", "Sales Tech", "E-Commerce", "Data Analytics"]
  },
  { 
    id: "baksters", 
    nameTh: "บริษัท แบ็คส์เตอร์ส จำกัด", 
    nameEn: "Bakster Company Limited", 
    logo: "https://martechthai.org/wp-content/uploads/2025/12/598047-Darin-Cheng.jpg", 
    businessType: "Consult", 
    contact: "ดารินทร์", 
    phone: "080-963-6451", 
    email: "darin.c@baksters.com", 
    website: "https://www.baksters.com/", 
    description: "BAKSTERS เป็นบริษัทที่ปรึกษาและพัฒนาซอฟต์แวร์ในประเทศไทย",
    tags: ["Consulting", "Software Development", "AI"]
  },
  { 
    id: "mekha", 
    nameTh: "บริษัท เมฆา อินโนเวชั่น จำกัด", 
    nameEn: "MEKHA INNOVATION CO., LTD.", 
    logo: "https://martechthai.org/wp-content/uploads/2025/12/WH-Hori-Logo-Theeraporn-Thaipakdee-1-scaled.jpg", 
    businessType: "Tech Platform", 
    contact: "สิทธิ เทียมเมฆา", 
    phone: "089-449-8687", 
    email: "sitthi@mekha.ai", 
    website: "https://mekha.ai/", 
    description: "เมฆา อินโนเวชั่น - ผู้พัฒนา Mekha.AI", 
    longLogo: true,
    tags: ["Tech Platform", "AI", "Cloud"]
  },
  { 
    id: "achi", 
    nameTh: "บริษัท อะชิ แอคทิเวชั่น จำกัด", 
    nameEn: "A CHI ACTIVATION CO., LTD.", 
    logo: "https://martechthai.org/wp-content/uploads/2025/12/new-logo-2024-A-CHI-Activation.png", 
    businessType: "Agency", 
    contact: "ชณพิชชา ศรีทอง", 
    phone: "06-1536-5666", 
    email: "nich@achi.co.th", 
    website: "https://www.achi.co.th", 
    description: "Marketing Service Solutions",
    tags: ["Event", "Activation", "Marketing Service"]
  },
  { 
    id: "digifuture", 
    nameTh: "บริษัท ดิจิฟิวเจอร์ จำกัด", 
    nameEn: "DigiFuture Company Limited", 
    logo: "https://martechthai.org/wp-content/uploads/2025/12/DFC-Company-Logo-Tanya-Phathanathong.png", 
    businessType: "Agency", 
    contact: "วีรวรรณ พัฒนทอง", 
    phone: "092-465-1542", 
    email: "tanya@dfcth.com", 
    website: "https://www.dfcth.com", 
    description: "DigiFuture bridges the gap between marketing and technology",
    tags: ["Digital Agency", "MarTech", "Consulting"]
  },
  { 
    id: "sparkjump", 
    nameTh: "บริษัท สปาร์คจั๊มพ์ เอเจนซี่ จำกัด", 
    nameEn: "SPARKJUMP AGENCY CO., LTD.", 
    logo: "https://martechthai.org/wp-content/uploads/2025/12/1logo-sparks-jump-Ampaiwan-Cher-1.png", 
    businessType: "Agency", 
    contact: "อำไพวรรณ สุธิราธิกุล", 
    phone: "085-801-2585", 
    email: "ampaiwansuthirathikul@gmail.com", 
    website: "https://www.sparksjump.com", 
    description: "ที่ปรึกษาดูแลการตลาดและธุรกิจ",
    tags: ["Consulting", "Digital Marketing", "SEO/SEM"]
  },
  { 
    id: "sable", 
    nameTh: "บริษัท เซเบิล จำกัด", 
    nameEn: "Sable Co., Ltd.", 
    logo: "https://martechthai.org/wp-content/uploads/2025/12/logo_sable-b-Phatarawadee-Tanasupjinda.png", 
    businessType: "Tech Platform", 
    contact: "อิศเรศ ประจิตต์มุทิตา", 
    phone: "094-698-7463", 
    email: "issaret@sable.asia", 
    website: "https://sable.asia/", 
    description: "SABLE คือ Agentic AI Marketing Cloud และแพลตฟอร์มข้อมูลลูกค้า (CDP)",
    tags: ["AI", "CDP", "Marketing Automation", "Tech Platform"]
  },
  { 
    id: "digiconnect", 
    nameTh: "บริษัท ดิจิคอนเน็คท์ จำกัด", 
    nameEn: "DigiConnect CO., LTD.", 
    logo: "https://martechthai.org/wp-content/uploads/2025/12/logo-png-Chatchawan-Kaewmanee.png", 
    businessType: "Agency", 
    contact: "ชัชวาล แก้วมณี", 
    phone: "083-074-4505", 
    email: "ceodigiconnect@gmail.com", 
    website: "https://www.digiconnect.co.th/", 
    description: "เอเจนซี่การตลาดดิจิทัลที่ขับเคลื่อนด้วยข้อมูล",
    tags: ["Digital Agency", "Data Driven", "Performance Marketing"]
  },
  { 
    id: "infilight", 
    nameTh: "บริษัท อินฟิไลท์ จำกัด", 
    nameEn: "Infilight co.,ltd", 
    logo: "https://martechthai.org/wp-content/uploads/2025/12/JordSabuy_Logo_RGB_Logo-Corporate-Vertical-Walaiwan-Suttapash.png", 
    businessType: "Tech Platform", 
    contact: "ธนภูมิ สุกัญจนศิริ", 
    phone: "085-046-2787", 
    email: "thanaphum.s@jordsabuy.com", 
    website: "https://jordsabuy.com", 
    description: "Jordsabuy (โดย Infilight) ระบบบริหารลานจอดรถอัจฉริยะ (Smart Parking) ช่วยจัดการสมาชิก/ลูกบ้าน และบันทึกข้อมูลการจอดด้วยเทคโนโลยี IoT",
    tags: ["Smart Parking", "IoT", "Tech Platform", "Management System"]
  }
];

const MARTECH_PERSONS = [
  { id: "p1", name: "คุณธีรพล อำไพ" },
  { id: "p2", name: "คุณชาติชาย มีสุขโข" },
  { id: "p3", name: "คุณรวิ อัญญากาญจน์" },
  { id: "p4", name: "คุณภรต หอมดอก" },
  { id: "p5", name: "คุณเอกพล สมเจริญ" },
  { id: "p6", name: "คุณปัณณทัต จอมจักร์" },
  { id: "p7", name: "คุณปรัชญ์ เหตระกูล" },
  { id: "p8", name: "คุณปรางสิริน พิมพ์กิตติ์สิริกุล" },
  { id: "p9", name: "คุณวนิดา เรืองลิขิตกุล" },
  { id: "p10", name: "คุณพิมพิกา คุณพรหม" },
  { id: "p11", name: "คุณอนุชิต พงศ์ภัทรานนท์" },
  { id: "p12", name: "คุณศิริพงษ์ สีใสไพร" },
  { id: "p13", name: "คุณธนัทพัชร์ ตั้งวงศ์ศิริ" }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { MARTECH_COMPANIES, MARTECH_PERSONS, MARTECH_POPULAR_TAGS };
}
